### ISSUE TITLE
Add button to email notifications to get more info about the suspicious ip

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/suspicious_login#801]
Hi!
I think it's good that the systems checks (and learns) about IP/Userid combinations.

- Nevertheless I think the message should be more helpful to allow a click on

https://www.whatismyip.com/ip-address-lookup/  + IP Address to quickly show the location - that's what the warning is advising.
At least it could give a hint, but may be not helpful for user-nomads with many different IP's

- it would also be good if the admin (or user) is able to see the table content.

**Comment by 0xErnie** [comment]
Am I right that you are reffering to e-mail messages?

There are already similar issues #270  and an idea like yours #209  has been implemented for the webinterface in #535.
You could adjust the title of your issue to maybe something like _add button to e-mail for more info about the suspicious ip_

I hope this can lead to a better ux - I am also here because of anoyed users with flooded inboxes.
